<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- 继承根工程的统一版本和构建配置。 -->
    <parent>
        <groupId>org.example</groupId>
        <artifactId>java-box</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>spring-boot</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Web 依赖：提供嵌入式 Tomcat、DispatcherServlet 和 Web 开发相关能力。 会帮我们自动导入 web 的所有依赖-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>  <!-- 会帮我们自动导入 web 的所有依赖 -->
        </dependency>

        <!-- Lombok 编译期工具，用于生成常用 Java 样板代码。 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Spring Boot 测试依赖，提供测试框架和常用测试工具，仅测试阶段使用。 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!--
            Spring Boot 配置处理器：
            为 @ConfigurationProperties 生成配置元数据，
            便于 IDEA 提供配置项自动补全和提示。
            optional=true 表示它只用于编译期，不会参与运行时依赖。
            不导入也没事，但是会有一个提示。如果使用 @Value("${dog.name}") 这种方式就没必要导入
            但是如果使用了 @ConfigurationProperties(prefix = "person") 那么建议导入
        -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Spring Boot 打包插件：将依赖和项目代码打入可执行 jar。 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <!-- 在 package 阶段重打包，使 JAR 能通过 java -jar 直接启动。 -->
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
